# Generated by Django 3.2.8 on 2021-10-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='visibility',
        ),
    ]
