# Generated by Django 3.2.7 on 2021-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=125, unique=True)),
                ('about', models.CharField(blank=True, max_length=160, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatars')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/covers')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
