# Generated by Django 3.2.7 on 2021-09-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('followers', 'only followers'), ('follow', 'only my subscriptions'), ('all', 'all')], default='all', max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='accounts.user')),
                ('users_like', models.ManyToManyField(blank=True, related_name='tweets_liked', to='accounts.User')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
