# Generated by Django 3.2.7 on 2021-09-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/tweets')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweets.tweets')),
            ],
        ),
    ]
